export const ActionType = {
  GET_ALL_USER_DATA: "GET_ALL_USER_DATA",
  GET_ALL_MALE_DATA: "GET_ALL_MALE_DATA",
  GET_ALL_FEMALE_DATA: "GET_ALL_FEMALE_DATA",
  SET_CATEGORY_DATA: "SET_CATEGORY_DATA",
  SET_CATEGORY_ITEM_DATA: "SET_CATEGORY_ITEM_DATA",
  GET_CATEGORY_ITEM_DATA: "GET_CATEGORY_ITEM_DATA",
};
